/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/competencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_competency"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/competencies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_competency"];
        options?: never;
        head?: never;
        patch: operations["update_competency"];
        trace?: never;
    };
    "/v1/development-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_dev_item"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/development-items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_dev_item"];
        options?: never;
        head?: never;
        patch: operations["update_dev_item"];
        trace?: never;
    };
    "/v1/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_goal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/goals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_goal"];
        options?: never;
        head?: never;
        patch: operations["update_goal"];
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_meeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/meetings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_meeting"];
        put?: never;
        post?: never;
        delete: operations["delete_meeting"];
        options?: never;
        head?: never;
        patch: operations["update_meeting"];
        trace?: never;
    };
    "/v1/meetings/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["complete_meeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/members/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_member"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/members/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_member_files"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/members/{id}/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_member_goals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/members/{id}/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_member_meetings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/teams/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_members"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/teams/{id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["team_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_template"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Competency: {
            /** Format: uuid */
            id: string;
            label: string;
            /** Format: int32 */
            score: number;
        };
        CreateCompetencyRequest: {
            label: string;
            /** Format: uuid */
            member_id: string;
            /** Format: int32 */
            score: number;
        };
        CreateDevItemRequest: {
            kind: string;
            /** Format: uuid */
            member_id: string;
            note?: string | null;
            status: string;
            title: string;
        };
        CreateGoalRequest: {
            /** Format: date-time */
            due: string;
            key_result: string;
            /** Format: uuid */
            member_id: string;
            /** Format: int32 */
            progress: number;
            quarter: string;
            status: string;
            title: string;
        };
        /** @description Create a new (planned) 1-2-1 for a member. */
        CreateMeetingRequest: {
            /**
             * Format: date-time
             * @description Defaults to now() when omitted.
             */
            date?: string | null;
            /** Format: uuid */
            member_id: string;
        };
        DevItem: {
            /** Format: uuid */
            id: string;
            kind: string;
            note?: string | null;
            status: string;
            title: string;
        };
        /** @description A meeting form field definition (from a template), for rendering the drawer. */
        FieldDef: {
            hint?: string | null;
            /** Format: uuid */
            id: string;
            kind: string;
            options: string[];
            /** Format: int32 */
            ord: number;
            placeholder?: string | null;
            required: boolean;
            title: string;
        };
        FileMeta: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            kind: string;
            meeting_label?: string | null;
            mime: string;
            name: string;
            /** Format: int64 */
            size_bytes: number;
            uploaded_by: string;
        };
        Goal: {
            /** Format: date-time */
            due: string;
            /** Format: uuid */
            id: string;
            key_result: string;
            /** Format: int32 */
            progress: number;
            quarter: string;
            status: string;
            title: string;
        };
        GoalsResponse: {
            competencies: components["schemas"]["Competency"][];
            development: components["schemas"]["DevItem"][];
            okrs: components["schemas"]["Goal"][];
        };
        /** @description Liveness/readiness payload returned by `GET /v1/health`. */
        Health: {
            status: string;
            version: string;
        };
        /** @description Login request body. */
        LoginRequest: {
            email: string;
            password: string;
        };
        /** @description Successful login payload. */
        LoginResponse: {
            token: string;
            user: components["schemas"]["UserDto"];
        };
        /** @description `/auth/me` response: the user plus the team they lead (if any). */
        MeResponse: {
            email: string;
            /** Format: uuid */
            id: string;
            name: string;
            role: string;
            /** Format: uuid */
            team_id?: string | null;
        };
        /** @description Expanded meeting for the MeetingDetailCard. */
        MeetingDetail: {
            blockers?: string | null;
            /** Format: date-time */
            date: string;
            development: string[];
            /** Format: int32 */
            duration_min: number;
            feedback_from?: string | null;
            feedback_to?: string | null;
            goals?: string | null;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            member_id: string;
            mood?: string | null;
            /** Format: int32 */
            mood_score?: number | null;
            relationships?: string | null;
            state: string;
            /** Format: uuid */
            template_id?: string | null;
        };
        /** @description One row in the History feed / calendar. */
        MeetingListItem: {
            /** Format: date-time */
            date: string;
            /** Format: uuid */
            id: string;
            mood?: string | null;
            /** Format: int32 */
            mood_score?: number | null;
            preview: string;
            state: string;
        };
        /** @description Full header for the EmployeeProfile screen. */
        MemberDetail: {
            email: string;
            /** Format: int32 */
            hue: number;
            /** Format: uuid */
            id: string;
            joined: string;
            /** Format: date-time */
            last_meet?: string | null;
            /** Format: int64 */
            meetings_total: number;
            mood_trend: number[];
            name: string;
            /** Format: date-time */
            next_meet?: string | null;
            role: string;
            status: string;
            tags: string[];
            tz: string;
        };
        /** @description A team member as shown in the TeamList table. */
        MemberRow: {
            email: string;
            /** Format: int32 */
            hue: number;
            /** Format: uuid */
            id: string;
            joined: string;
            /** Format: date-time */
            last_meet?: string | null;
            mood_trend: number[];
            name: string;
            /** Format: date-time */
            next_meet?: string | null;
            role: string;
            status: string;
            tags: string[];
            tz: string;
        };
        /** @description The 4 TeamList stat cards. */
        TeamStats: {
            /** Format: double */
            avg_mood: number;
            /** Format: double */
            avg_mood_delta: number;
            /** Format: int64 */
            notes_quarter: number;
            /** Format: int64 */
            overdue: number;
            /** Format: int64 */
            this_week: number;
        };
        TemplateDetail: {
            fields: components["schemas"]["FieldDef"][];
            /** Format: uuid */
            id: string;
            name: string;
        };
        UpdateCompetencyRequest: {
            label?: string | null;
            /** Format: int32 */
            score?: number | null;
        };
        UpdateDevItemRequest: {
            kind?: string | null;
            note?: string | null;
            status?: string | null;
            title?: string | null;
        };
        UpdateGoalRequest: {
            /** Format: date-time */
            due?: string | null;
            key_result?: string | null;
            /** Format: int32 */
            progress?: number | null;
            quarter?: string | null;
            status?: string | null;
            title?: string | null;
        };
        /** @description Autosave patch — every field optional; provided fields are written. */
        UpdateMeetingRequest: {
            blockers?: string | null;
            /** Format: date-time */
            date?: string | null;
            development?: string[] | null;
            /** Format: int32 */
            duration_min?: number | null;
            feedback_from?: string | null;
            feedback_to?: string | null;
            goals?: string | null;
            mood?: string | null;
            /** Format: int32 */
            mood_score?: number | null;
            relationships?: string | null;
        };
        /** @description Public user shape returned to the client. */
        UserDto: {
            email: string;
            /** Format: uuid */
            id: string;
            name: string;
            role: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_competency: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCompetencyRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competency"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_competency: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competency id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_competency: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Competency id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCompetencyRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competency"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_dev_item: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDevItemRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevItem"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_dev_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Dev item id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_dev_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Dev item id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDevItemRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevItem"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_goal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGoalRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Goal"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_goal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Goal id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_goal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Goal id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGoalRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Goal"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    create_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMeetingRequest"];
            };
        };
        responses: {
            /** @description Created planned meeting */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingDetail"];
                };
            };
            /** @description Member not on the caller's team */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Meeting id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Meeting detail (all note fields) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingDetail"];
                };
            };
            /** @description Meeting's member not on the caller's team */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such meeting */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Meeting id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Meeting's member not on the caller's team */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such meeting */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cannot delete a completed meeting */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Meeting id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeetingRequest"];
            };
        };
        responses: {
            /** @description Updated meeting */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingDetail"];
                };
            };
            /** @description Invalid payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Meeting's member not on the caller's team */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such meeting */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    complete_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Meeting id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Completed meeting */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingDetail"];
                };
            };
            /** @description Meeting's member not on the caller's team */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such meeting */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Meeting is not planned */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_member: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Member id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member detail (profile header) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberDetail"];
                };
            };
            /** @description Member not on the caller's team */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such member */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_member_files: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Member id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File metadata (read-only) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileMeta"][];
                };
            };
            /** @description Member not on the caller's team */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_member_goals: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Member id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OKRs + dev plan + competencies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalsResponse"];
                };
            };
            /** @description Member not on the caller's team */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_member_meetings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Member id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All meetings, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingListItem"][];
                };
            };
            /** @description Member not on the caller's team */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_members: {
        parameters: {
            query?: {
                /** @description Search name or role */
                q?: string;
                /** @description Exact role */
                role?: string;
                /** @description new | mid | sen */
                tenure?: string;
                /** @description up | flat | down */
                mood?: string;
                /** @description lt1w | lt2w | gt4w */
                since?: string;
                /** @description comma-separated tags */
                tags?: string;
            };
            header?: never;
            path: {
                /** @description Team id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Team members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberRow"][];
                };
            };
            /** @description Not the team's lead */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    team_stats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Team stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamStats"];
                };
            };
            /** @description Not the team's lead */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_template: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Template id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Template with ordered field defs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateDetail"];
                };
            };
            /** @description No such template */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
